### ISSUE TITLE
import *..... please don't

### ISSUE THREAD

**Issue by PySimpleGUI** [Carlosj50/ORGANIZADORAUTOMATICO_GUI#1]
I know a lot of examples show 
```python
from package import *
```

But there is not one example in the PySimpleGUI project that shows doing this.  Don't do it with PySimpleGUI.  It's a really bad thing to do (I almost never say something is truly "bad" to do, but this one is)

If you REALLY don't want to have to type "sg." in front of elements, etc, then copy these to the top of your code instead of the import *:

```python
import PySimpleGUI as sg
# Import the Elements, Window and SystemTray classes
from PySimpleGUI import Input, Combo, OptionMenu, Listbox, Radio, Checkbox, Spin, Multiline, Text, StatusBar, Output, Button, ButtonMenu, ProgressBar, Image, Canvas, Graph, Frame, VerticalSeparator, HorizontalSeparator, Tab, TabGroup, Slider, Column, Pane, Menu, Table, Tree, Window, SystemTray
# Import the short versions and other stuff that are not elements like popup and the Browse buttons
from PySimpleGUI import I, In, InputText, DD, Drop, DropDown, InputCombo, InputOptionMenu, LB, LBox, R, Rad, CB, CBox, Check, Sp, ML, MLine, T, Txt, SBar, B, Btn, BM, BMenu, PBar, Prog, Progress, Im, G, Fr, VSep, VSeparator, VSeperator, HSep, HSeparator, Sl, Col, MenuBar, FolderBrowse, FileBrowse, popup

```

Then you can drop the `sg.` in your layouts, etc.

**Comment by Carlosj50** [comment]
Ok, I keep that in mind. I will import as they comment. Just one question:
Why is it so bad?

**Comment by PySimpleGUI** [comment]
It "trashes your namespace".

One reason is clarity.  The reader of the code wants to know where something is coming from.  When Text is used, what module supplied it?  With import *, you have no idea.

There are a number of good articles written about it.  They're worth taking a moment to glance at.

It's unfortunate that SO MANY of the tkinter examples teach people to do this.  It's why I made it a mission to make sure and never do that with PySimpleGUI and to discourage doing it.

When a more experienced Python programmer reads code and see this statement, they immediately categorize the developer as being a junior developer.  It doesn't advertise yourself as being as skilled as you likely really are.  😁

**Comment by Carlosj50** [comment]
I'm not a junior .. I'm still learning .. Thank you very much for the
clarification. I write it down. And I put it into practice.

**Comment by Carlosj50** [comment]
A question. I am in a study group that uses Python. And they ask me: How
could you contact me if I am not even an active programmer?

**Comment by PySimpleGUI** [comment]
I'm still learning too!  I learn from complete beginners as well as more experienced engineers.

It's great you're open to learning, serious about actually doing things with what you learn.  PLEASE keep making GUIs!

Oh, and share the screenshot of what you make!  The video is in English, but I made a video on how to put them into your readme file:
https://youtu.be/C4PVKW756fo

>  How could you contact me if I am not even an active programmer?

You're an active programmer!  I read your code.   That's why I contacted you.  The code you wrote and posted here is what I saw.  I think that makes you an "active programmer"

**Comment by Carlosj50** [comment]
Fixed import and module dependent elements. A greeting.

**Comment by Carlosj50** [comment]
I am new to this, even though I am already 50 years old. And the best way
to learn is by listening and paying attention to the best. Thanks to you.

**Comment by PySimpleGUI** [comment]
Ah, wise you are too!  I'm over 50 and new to Python too.  I started learning Python in Oct 2017 which puts me out ahead by 3 years.  The stuff I'm telling you now, you'll be passing on to the other newcomers to Python in a few months.

**Comment by Carlosj50** [comment]
😀😊
